import type { SeoCluster } from "@/content/seo/types";

export const CLUSTER_LABELS: Record<SeoCluster, string> = {
  "anki-alternative": "Anki Alternatives",
  "pdf-to-flashcards": "PDF to Flashcards",
  "medical-students": "Medical Students",
  "exam-preparation": "Exam Preparation",
  "spaced-repetition": "Spaced Repetition",
  "ai-study-tools": "AI Study Tools",
  "active-recall": "Active Recall",
  "productivity": "Study Productivity",
};

export const SEO_SLUGS = [
  "anki-alternative",
  "best-anki-alternative",
  "anki-vs-smartflashcards",
  "online-anki-alternative",
  "ai-powered-anki-alternative",
  "anki-for-beginners",
  "pdf-to-flashcards",
  "convert-pdf-to-flashcards",
  "ai-pdf-to-flashcards",
  "create-flashcards-from-pdf",
  "study-pdf-faster",
  "pdf-learning-tool",
  "flashcards-for-medical-school",
  "medical-school-flashcards",
  "anatomy-flashcards",
  "pharmacology-flashcards",
  "medical-study-ai",
  "medical-exam-preparation",
  "flashcards-for-exams",
  "study-for-exams-with-ai",
  "exam-preparation-techniques",
  "how-to-study-for-finals",
  "revision-techniques-for-exams",
  "ai-study-assistant",
  "spaced-repetition",
  "what-is-spaced-repetition",
  "how-spaced-repetition-works",
  "spaced-repetition-software",
  "memory-retention-techniques",
  "long-term-memory-learning",
  "ai-study-tools",
  "best-ai-tools-for-students",
  "chatgpt-for-studying",
  "ai-learning-platform",
  "ai-flashcard-generator",
  "ai-for-learning",
  "active-recall",
  "active-recall-technique",
  "how-to-use-active-recall",
  "active-recall-vs-passive-learning",
  "active-learning-methods",
  "how-to-remember-more",
  "how-to-study-more-efficiently",
  "how-to-learn-faster",
  "better-study-habits",
  "study-productivity-tips",
  "smart-study-methods",
  "effective-learning-strategies",
] as const;

export type SeoSlug = (typeof SEO_SLUGS)[number];
